# Generated by Django 4.2 on 2023-04-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_equipo_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='estado',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Activa', 'Activa'), ('Pendiente', 'Pendiente'), ('Baja', 'Baja')], max_length=20),
        ),
    ]
